
$bg = rgb({{ colors.background.default.hex_stripped }})
$border = rgba({{ colors.outline.default.hex_stripped }}88) rgba({{ colors.background.default.hex_stripped }}ff) 45deg
$primary = rgb({{ colors.primary.default.hex_stripped }})
$error = rgb({{ colors.error.default.hex_stripped }})

general {
  col.active_border = $border
  col.inactive_border = $bg
}

group {
  col.border_active = $border
  col.border_inactive = $bg
  col.border_locked_active = $error
  col.border_locked_inactive = $bg

  groupbar {
    col.active = $primary
    col.inactive = $bg
    col.locked_active = $error
    col.locked_inactive = $bg
  }
}
