## modules/desktop/hyprland.nix
#
# Sets up a hyprland-based desktop environment.

{ hey, heyBin, lib, options, config, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.desktop.hyprland;
    primaryMonitor = findFirst (x: x.primary) {} cfg.monitors;
in {
  options.modules.desktop.hyprland = with types; {
    enable = mkBoolOpt false;
    extraConfig = mkOpt lines "";
    monitors = mkOpt (listOf (submodule {
      options = {
        output = mkOpt str "";
        mode = mkOpt str "preferred";
        position = mkOpt str "auto";
        scale = mkOpt int 1;
        disable = mkOpt bool false;
        primary = mkOpt bool false;
      };
    })) [{}];
  };

  config = mkIf cfg.enable {
    modules.desktop.enable = true;

    environment.systemPackages = with pkgs; [
      ## For Hyprland & DMS
      xrandr         # for XWayland windows
      adw-gtk3       # for DMS

      ## For CLIs
      gromit-mpx     # for drawing on the screen
      pamixer        # for volume control
      wlr-randr      # for monitors that hyprctl can't handle
      wf-recorder    # for screencasting
    ];

    environment.sessionVariables = {
      ELECTRON_OZONE_PLATFORM_HINT = "auto";
      NIXOS_OZONE_WL = "1";
      MOZ_ENABLE_WAYLAND = "1";
      QT_QPA_PLATFORMTHEME = "gtk3";
      QT_QPA_PLATFORMTHEME_QT6 = "gtk3";
    };

    programs.hyprland = {
      enable = true;
      withUWSM = true;
      systemd.setPath.enable = true;
    };

    programs.dms-shell = {
      enable = true;
      systemd = {
        enable = true;
        restartIfChanged = true;
      };
      enableSystemMonitoring = true;
      enableDynamicTheming = true;
    };

    services.greetd = {
      enable = true;
      settings.default_session = {
        command = "uwsm start -eD Hyprland hyprland.desktop";
        user = config.user.name;
      };
    };

    hey = {
      info.hypr = {
        primaryMonitor = primaryMonitor.output or null;
        monitors = cfg.monitors;
      };
      hooks = rec {
        # Launch my hyprlock-powered, pseudo-login screen on `hey hook
        # on-startup`.
        startup."05-startup-sound" = ''
          hey .play-sound startup
        '';

        # I'm using this instead of exec= lines in hyprland.conf so I can ensure
        # these aren't run at startup and sequentially (i.e. predictable order,
        # since Hyprland's exec= calls are parallelized).
        reload."95-hyprland" = ''
          for i in $(hyprctl instances -j | jq -r '.[].instance'); do
            echo "Hyprland: reloading instance $i"
            hey.do hyprctl -i ''${i//*\//} reload config-only
          done
        '';
      };
    };

    home.configFile = {
      "matugen/templates".source = "${hey.configDir}/matugen/templates";

      "matugen/config.toml".text = ''
        [config]
        version_check = false
        import_json_files = ["~/.config/matugen/custom.json"]

        [templates.hyprland]
        input_path = "${hey.configDir}/matugen/templates/hyprland.conf"
        output_path = "~/.config/hypr/hyprland.colors.conf"

        ${optionalString config.modules.shell.tmux.enable ''
          [templates.tmux]
          input_path = "${hey.configDir}/matugen/templates/tmux.conf"
          output_path = "~/.config/tmux/dank-colors.conf"
        ''}
        ${optionalString config.modules.desktop.apps.rofi.enable ''
          [templates.rofi]
          input_path = "${hey.configDir}/matugen/templates/rofi.rasi"
          output_path = "~/.config/rofi/themes/dank-colors.rasi"
        ''}
        ${optionalString config.modules.desktop.term.foot.enable ''
          [templates.foot]
          input_path = "${hey.configDir}/matugen/templates/foot.ini"
          output_path = "~/.config/foot/dank-colors.ini"
        ''}
      '';

      "matugen/custom.json".text = ''
        {
          "fonts": {
            "mono": "JetBrainsMono Nerd Font",
            "sans": "Fira Sans"
          }
        }
      '';

      "hypr" = {
        source = "${hey.configDir}/hypr";
        recursive = true;
      };

      "hypr/hyprland.pre.conf".text = ''
        # config/hypr/hyprland.pre.conf
        # This was automatically generated by NixOS and my dotfiles

        # Bootstrap session
        exec-once = hey hook startup

        ${concatStringsSep "\n" (map
          (v: if v.disable
              then "monitor = ${v.output},disable"
              else "monitor = ${v.output},${v.mode},${v.position},${toString v.scale}")
          cfg.monitors)}

        $PRIMARY_MONITOR = ${primaryMonitor.output or ""}
        ${optionalString (primaryMonitor ? output) ''
          cursor {
            default_monitor = $PRIMARY_MONITOR
          }

          workspace=1,monitor:$PRIMARY_MONITOR,default:true,persistent:true
          workspace=2,monitor:$PRIMARY_MONITOR
          workspace=3,monitor:$PRIMARY_MONITOR
          workspace=4,monitor:$PRIMARY_MONITOR
          workspace=5,monitor:$PRIMARY_MONITOR
          workspace=6,monitor:$PRIMARY_MONITOR
          workspace=7,monitor:$PRIMARY_MONITOR
          workspace=8,monitor:$PRIMARY_MONITOR
          workspace=9,monitor:$PRIMARY_MONITOR,layout:monocle,no_border:true,no_shadow:true,gaps_in:0,gaps_out:0

          # Since wayland doesn't have the concept of a primary monitor,
          # XWayland windows may start in unpredictable places without a hint.
          exec-once = xrandr --output $PRIMARY_MONITOR --primary
        ''}
      '';
      "hypr/hyprland.post.conf".text = cfg.extraConfig;
    };

    user.packages = with pkgs; [
      # (catppuccin-kvantum.override {
      #   variant = "mocha";
      #   accent = "maroon";
      # })
      # (graphite-gtk-theme.override {
      #   themeVariants = [ "pink" ];
      #   colorVariants = [ "dark" ];
      #   # sizeVariants = [ "compact" ];
      #   tweaks = [
      #     "normal"
      #     "rimless"
      #     "darker"
      #   ];
      # })
      (catppuccin-papirus-folders.override {
        flavor = "mocha";
        accent = "maroon";
      })
      catppuccin-cursors.mochaDark
      tela-circle-icon-theme

      (mkLauncherEntry "Toggle night mode" {
        icon = "redshift";
        exec = "dms ipc night toggle";
      })
      (mkLauncherEntry "Color picker: grab RGB at point" {
        icon = "com.github.finefindus.eyedropper";
        exec = "dms color pick --rgb -a";
      })
      (mkLauncherEntry "Color picker: grab HSL at point" {
        icon = "com.github.finefindus.eyedropper";
        exec = "dms color pick --hsl -a";
      })
      (mkLauncherEntry "Color picker: grab hex at point" {
        icon = "com.github.finefindus.eyedropper";
        exec = "dms color pick --hex -a";
      })
    ];
  };
}
