## modules/desktop/matugen.nix
#
# Generates color schemes for various apps based on your current theme. DMS
# regenerates its templates when the wallpaper changes.

{ hey, lib, config, options, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.desktop.matugen;

    escapeStr = builtins.toJSON;  # JSON strings == TOML strings

    mkColor = name: v: ''
      [config.custom_colors.${name}]
      color = ${escapeStr (if isString v then v else v.color)}
      blend = ${boolToString (if isString v then true else v.blend)}
    '';

    mkTemplate = name: v: concatStrings (
      [ "[templates.${name}]\n"
        "input_path = ${escapeStr v.input_path}\n" ]
      ++ optional (v.output_path != "") "output_path = ${escapeStr v.output_path}\n"
      ++ optional (v.pre_hook    != "") "pre_hook = ${escapeStr v.pre_hook}\n"
      ++ optional (v.post_hook   != "") "post_hook = ${escapeStr v.post_hook}\n");

in {
  options.modules.desktop.matugen = with types; {
    colors = mkOpt' (attrsOf (either str (submodule {
      options = {
        color = mkOpt' str  ""   "A CSS hex color to seed the palette with";
        blend = mkOpt' bool true "Whether to harmonize the color with the scheme";
      };
    }))) {} "Seed colors to harmonize into the generated scheme";

    templates = mkOpt' (attrsOf (submodule {
      options = {
        input_path  = mkOpt' str   "" "The template to render";
        output_path = mkOpt' str   "" "Where to write the rendered template";
        pre_hook    = mkOpt' lines "" "Shell run before the template is written";
        post_hook   = mkOpt' lines "" "Shell run after the template is written";
      };
    })) {} "Templates for matugen to render when the theme changes";
  };

  config = mkIf (cfg.templates != {} || cfg.colors != {}) {
    home.configFile = {
      "matugen/templates".source = "${hey.configDir}/matugen/templates";

      "matugen/config.toml".text = concatStringsSep "\n" ([
        "# Auto-generated by nixos"
        "[config]"
        "version_check = false"
        "import_json_files = [${escapeStr "${config.home.dataDir}/hey/info.json"}]"
        ""
      ] ++ mapAttrsToList mkColor cfg.colors ++ [
        "# matugen requires this table, even with no templates under it."
        "[templates]"
        ""
      ] ++ mapAttrsToList mkTemplate cfg.templates);
    };
  };
}
